### ISSUE TITLE
Translation missing in lib/eol/eol/sparql/client.rb line 80

### ISSUE THREAD

**Issue by aka001** [EOL/eol#112]
https://github.com/EOL/eol/blob/master/lib/eol/sparql/client.rb#L80
Shouldn't this message be stored in config/translations/en.yml file and the variable must be used here instead ? 
@dimus @JRice Do you have any comments on this?

**Comment by JRice** [comment]
No. This message (and others like it) are "puts"ed, and thus only stored in the logs, never displayed to a user.

Honestly, this block should use Rails.logger.error instead of puts, but it needn't use translations, as EOL is not intended for administration in other languages.

**Comment by aka001** [comment]
@JRice Thank you for the reply. So, should I create a pr which uses Rails.logger.error instead of "puts"ing the message?

**Comment by JRice** [comment]
No. Based on your comment I just made the change myself. :) Thanks, though!

**Comment by aka001** [comment]
@JRice Ya I saw it. no problem. :)
