### ISSUE TITLE
Schemas are no longer public

### ISSUE THREAD

**Issue by timrobertson100** [EOL/eol#141]
Please see these which return `403`
  http://eol.org/schema/media_extension.xml
  http://eol.org/schema/reference_extension.xml

Until a couple of days ago these were public and they are necessary for anyone following the data publishing guidelines.  It looks like everything in the `schema` directory is now returning `403`.

**Comment by timrobertson100** [comment]
This appears partially fixed today, but not completely.  
Repeated calls vary between `200` and `403`.

**Comment by timrobertson100** [comment]
I suspect some caches have just timed out.  Appears fixed now.

**Comment by eliagbayani** [comment]
Sorry for the inconvenience.
Seems some Smithsonian network hiccups from a longer disruption the other day.

**Comment by timrobertson100** [comment]
I'm afraid this continues.  Please see below.

Looking at your headers, my hunch is varnish has cached a bad backend response.  Can you please purge your varnish cache for these objects?


```
MacBook-Pro:~ tim$ curl http://eol.org/schema/reference_extension.xml
<html>
<head><title>403 Forbidden</title></head>
<body bgcolor="white">
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx/1.10.1</center>
</body>
</html>
```

**Comment by JRice** [comment]
Should be fixed now. Apologies.

**Comment by timrobertson100** [comment]
Thanks Jeremy. 
I'll close the issue, and if the monitoring alerts again reopen it.
