### ISSUE TITLE
EOL API: 'page' parameter using 'search' method shows no effect

### ISSUE THREAD

**Issue by AZweifels** [EOL/eol#143]
Using the 'search' method of the EOL API, I found the 'page' parameter having no impact on the returned results.

Example:

Searching for "Robin", the [page 1 results](http://eol.org/api/search/1.0.json?q=robin&page=1&exact=false&filter_by_taxon_concept_id=&filter_by_hierarchy_entry_id=&filter_by_string=&cache_ttl=) are exactly the same as the [page 2 results](http://eol.org/api/search/1.0.json?q=robin&page=2&exact=false&filter_by_taxon_concept_id=&filter_by_hierarchy_entry_id=&filter_by_string=&cache_ttl=).

**Comment by jhammock** [comment]
Apologies! You've caught us in maintenance mode while we are working on our v3 release. I may be able to offer you a workaround if you can use a download. Can you tell me any more about your use case?

**Comment by AZweifels** [comment]
Thanks for your reply despite working on v3. In my case, I'm using the eol API to search for taxonids related to given scientific names (a list of ~1600). The amount of total results often exceeds 30 so I'm requesting the results in batches using the 'pages=%i' parameter. Whereas the 'startIndex' seems to be properly set, the returned results are always exactly the same, i.e., the first 30 results of page=1 (cp. with the example in my first post).

As workaround I'm currently using the search function of the eol main page, e.g., [search for 'Robin'](http://www.eol.org/search?q=robin&search=Go) and scraping the returned html. However, using the API would be more convenient.

**Comment by jhammock** [comment]
Looks like you won't need a workaround; this should be working now. Thanks for reporting! You may be the first user to ever paginate this service...
