### ISSUE TITLE
http://eol.org/schema/media_extension.xml

### ISSUE THREAD

**Issue by timrobertson100** [EOL/eol#145]
Please can you fix this asap?  
It breaks live infrastructure for the GBIF network

http://eol.org/schema/media_extension.xml
http://eol.org/schema/reference_extension.xml

**Comment by MattBlissett** [comment]
With this PR: https://github.com/gbif/rs.gbif.org/pull/69 the files were added to GBIF's schema repository: https://rs.gbif.org/extension/eol/
